### ISSUE TITLE
Проверка лабраторной работы

### ISSUE THREAD

**Issue by alexgorovenko** [aleksgorovenko/lab2#1]
To: @evgeny-p

**Comment by evgeny-p** [comment]
Замечания:
1. Артефакты сборки не следует коммитить в репозиторий. Исполняемый файл нужно удалить.
2. Замечания по оформлению кода написаны в комментариях: https://github.com/aleksgorovenko/lab2/commit/e6e325bb9cf58abc67dc8f593616a140c74aa547
3. Заголовки коммитов начинаются с маленькой буквы.
4. В коммите https://github.com/aleksgorovenko/lab2/commit/f90e40abd470775fb1b8ad7278fd17d551733557 слишком много изменений: как функциональные, как и исправления ошибок, не относящился к новому функционалу.
5. Decision — это принятие решения при выборе. Решение задачи — solution.

Для сдачи работы нужно исправить первые два пункта.

**Comment by evgeny-p** [comment]
Принято.

Новую задачу создавать не стоило: обсуждение ведется в рамках одного задания. Сейчас закрывать можно обе.
